using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WindowsFormsApplication1 {
    class FMC_320 {
        public static PdfPTable Init_Page(DataRow row) {

            try {
                PdfPTable tableSetup = new PdfPTable(3);
                tableSetup.WidthPercentage = 100;
                tableSetup.SetWidths(new Single[] { 5, 1, 5});
                tableSetup.SpacingBefore = 0;

                // title
                Phrase pSetup = new Phrase("INIT A");
                pSetup.Font.Color = PDF.color_White;
                pSetup.Font.SetFamily(PDF.sFont_Fixed_Width);
                pSetup.Font.SetStyle("bold");
                pSetup.Font.Size = PDF.iNormalFontSize;
                PdfPCell cSetup = new PdfPCell(pSetup);
                cSetup.BackgroundColor = PDF.color_Black;//background_grey;
                cSetup.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup.Colspan = 3;
                tableSetup.AddCell(cSetup);

                // row 1/a
                var chuckC = new Chunk();
                var chuckL = new Chunk("CO RTE", PDF.font_Title_White_small);
                var chuckR = new Chunk("FROM / TO", PDF.font_Title_White_small);

                Phrase pSetup1 = new Phrase(chuckL);
                PdfPCell cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                Phrase pSetup2 = new Phrase(chuckC);
                PdfPCell cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                Phrase pSetup1d = new Phrase(chuckR);
                PdfPCell cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("NONE", PDF.font_Title_Cyan);
                chuckR = new Chunk(row["DEP"].ToString() + "/" + row["DEST"].ToString(), PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("ALTN / CO RTE", PDF.font_Title_White_small);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                if (row["ALTN"].ToString() != "")
                    chuckL = new Chunk(row["ALTN"].ToString(), PDF.font_Title_Cyan);
                else
                    chuckL = new Chunk("----/--------", PDF.font_Title_White_small);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("FLT NBR", PDF.font_Title_White_small);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("AAL" + row["FLTNUM"].ToString(), PDF.font_Title_Cyan);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk(" ", PDF.font_Title_Cyan);
                chuckR = new Chunk(" ", PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk(" ", PDF.font_Title_Cyan);
                chuckR = new Chunk(" ", PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("COST INDEX", PDF.font_Title_White_small);
                chuckR = new Chunk("TROPO", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk(row["CI"].ToString(), PDF.font_Title_Cyan);
                chuckR = new Chunk("36080", PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("CRZ FL / TEMP", PDF.font_Title_White_small);
                chuckR = new Chunk("GND TEMP", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("FL" + row["CRZALT"].ToString() + "/-40°", PDF.font_Title_Cyan);
                chuckR = new Chunk(row["TEMP"].ToString().Substring(0, row["TEMP"].ToString().IndexOf("/")) + "°", PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                return tableSetup;

            } catch (Exception) {
                throw;
            }
        }

        public static PdfPTable AC_Performance(DataRow row) {


            try {

                PdfPTable tableSetup = new PdfPTable(3);
                tableSetup.WidthPercentage = 100;
                tableSetup.SetWidths(new Single[] { 5, 1, 5 });
                tableSetup.SpacingBefore = 0;

                // title pdfPage
                Phrase pSetup = new Phrase("INIT B");
                pSetup.Font.Color = PDF.color_White;
                pSetup.Font.SetFamily(PDF.sFont_Fixed_Width);
                pSetup.Font.SetStyle("bold");
                pSetup.Font.Size = PDF.iNormalFontSize;
                PdfPCell cSetup = new PdfPCell(pSetup);
                cSetup.BackgroundColor = PDF.color_Black;//background_grey;
                cSetup.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup.Colspan = 3;
                tableSetup.AddCell(cSetup);

                // row 1/a
                var chuckC = new Chunk();
                var chuckL = new Chunk("TAXI", PDF.font_Title_White_small);
                var chuckR = new Chunk("ZFW / ZFWCG", PDF.font_Title_White_small);

                Phrase pSetup1 = new Phrase(chuckL);
                PdfPCell cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                Phrase pSetup2 = new Phrase(chuckC);
                PdfPCell cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                Phrase pSetup1d = new Phrase(chuckR);
                PdfPCell cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk(row["FUEL_TAXI"].ToString(), PDF.font_Title_Cyan);
                chuckR = new Chunk(row["ZFW"].ToString() + "/" + row["ZFWCG"].ToString(), PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("TRIP / TIME", PDF.font_Title_White_small);
                chuckR = new Chunk("BLOCK", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("----/----", PDF.font_Title_White);
                chuckR = new Chunk(PDF.Justify_Fuel(row["FUEL"].ToString()), PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("RTE RSV / %", PDF.font_Title_White_small);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("---.-/0", PDF.font_Title_White);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("ALTN / TIME", PDF.font_Title_White_small);
                chuckR = new Chunk("TOW  /   LW", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                if (row["FUEL_ALTN"].ToString() != "")
                    chuckL = new Chunk(row["FUEL_ALTN"].ToString() + "/0040", PDF.font_Title_Cyan);
                else
                    chuckL = new Chunk("---.-/----", PDF.font_Title_White);
                chuckR = new Chunk(row["GTOW"].ToString() + "/120.0", PDF.font_Title_Cyan);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("FINAL / TIME", PDF.font_Title_White_small);
                chuckR = new Chunk("TRIP WIND", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("---.-/0045", PDF.font_Title_Cyan);
                chuckR = new Chunk("---------", PDF.font_Title_White);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("MIN DEST FOB", PDF.font_Title_White_small);
                chuckR = new Chunk("EXTRA / TIME", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("--.-", PDF.font_Title_White);
                chuckR = new Chunk("---.-/----", PDF.font_Title_White);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                return tableSetup;

            } catch (Exception) {
                throw;
            }
        }

        public static PdfPTable Perf_TO(DataRow row) {
            try {

                PdfPTable tableSetup = new PdfPTable(3);
                tableSetup.WidthPercentage = 100;
                tableSetup.SetWidths(new Single[] { 4, 2, 4 });
                tableSetup.SpacingBefore = 0;

                // title pdfPage
                Phrase pSetup = null;
                if (row["THRUST"].ToString().Contains("FLEX"))
                    pSetup = new Phrase("UPLINK FLX TO DATA");
                else
                    pSetup = new Phrase("UPLINK MAX TO DATA");
                pSetup.Font.Color = PDF.color_White;
                pSetup.Font.SetFamily(PDF.sFont_Fixed_Width);
                pSetup.Font.SetStyle("bold");
                pSetup.Font.Size = PDF.iNormalFontSize;
                PdfPCell cSetup = new PdfPCell(pSetup);
                cSetup.BackgroundColor = PDF.color_Black;
                cSetup.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup.Colspan = 3;
                tableSetup.AddCell(cSetup);

                // row 1/a
                var chuckC = new Chunk();
                var chuckL = new Chunk("TOW / TOCG", PDF.font_Title_White_small);
                var chuckR = new Chunk("SHIFT/RWY", PDF.font_Title_White_small);

                Phrase pSetup1 = new Phrase(chuckL);
                PdfPCell cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                Phrase pSetup2 = new Phrase(chuckC);
                PdfPCell cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                Phrase pSetup1d = new Phrase(chuckR);
                PdfPCell cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk(row["GTOW"].ToString() + "/" + row["TOWCG"].ToString(), PDF.font_Title_Green);
                chuckR = new Chunk("     " + row["RUNWAY"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                string sLabel= "TEMP";
                if (row["THRUST"].ToString().Contains("FLEX")) {
                    sLabel = "FLEX";
                }
                chuckL = new Chunk(sLabel + " / QNH", PDF.font_Title_White_small);
                chuckC = new Chunk("V1", PDF.font_Title_White_small);
                chuckR = new Chunk("TO LIMITS", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                string sFlex="";
                if (row["THRUST"].ToString().Contains("FLEX")) {
                    // get the flex temp only
                    sFlex = row["THRUST"].ToString().Substring(row["THRUST"].ToString().IndexOf("+"), 3) + "°";
                } else {
                    // max data
                    sFlex = row["TEMP"].ToString().Substring(0, row["TEMP"].ToString().IndexOf("/")) + "°";
                }
                string sQnh = row["QNH"].ToString();
                if (sQnh.Contains("A"))
                    sQnh = sQnh.Substring(1);
                chuckL = new Chunk(sFlex + "/" + sQnh, PDF.font_Title_Green);
                chuckC = new Chunk(row["V1"].ToString(), PDF.font_Title_Green);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("MAG WIND", PDF.font_Title_White_small);
                chuckC = new Chunk("VR", PDF.font_Title_White_small);
                chuckR = new Chunk("FLAPS / THS", PDF.font_Title_White_small);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                string sWind = row["WIND"].ToString();
                if (sWind.Contains("KT"))
                    sWind = sWind.Substring(0, 3) + "°/" + sWind.Substring(3);
                sWind = sWind.Substring(0, sWind.IndexOf("K"));
                chuckL = new Chunk(sWind, PDF.font_Title_Green);
                chuckC = new Chunk(row["VR"].ToString(), PDF.font_Title_Green);
                chuckR = new Chunk(row["FLAPS"].ToString() + "/" + row["STAB"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("CONTAM", PDF.font_Title_White_small);
                chuckC = new Chunk("V2", PDF.font_Title_White_small);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                string sRcam = "WET";
                if (row["RUNWAY_COND"].ToString().Contains("6"))
                    sRcam = "DRY";
                chuckL = new Chunk(sRcam, PDF.font_Title_Green);
                chuckC = new Chunk(row["V2"].ToString(), PDF.font_Title_Green);
                chuckR = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_CENTER;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk("THR RED/ACC", PDF.font_Title_White_small);
                chuckR = new Chunk("ENG OUT ACC", PDF.font_Title_White_small);
                chuckC = new Chunk();
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_BOTTOM;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                chuckL = new Chunk(row["THRUST_RED_ALT"].ToString() + "/" + row["ACCEL_ALT"].ToString(), PDF.font_Title_Green);
                chuckR = new Chunk(row["EO_ACCEL_ALT"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckL);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup2 = new Phrase(chuckC);
                cSetup2 = new PdfPCell(pSetup2);
                cSetup2.BackgroundColor = PDF.color_Black;
                cSetup2.VerticalAlignment = Element.ALIGN_TOP;
                cSetup2.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup2.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup2);
                pSetup1d = new Phrase(chuckR);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_TOP;
                cSetup1d.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup1d.Colspan = 2;
                tableSetup.AddCell(cSetup1d);

                return tableSetup;

            } catch (Exception) {
                throw;
            }
        }

        public static PdfPTable Conditions_WX(DataRow row) {
            try {
                PdfPTable tableSetup = new PdfPTable(6);
                tableSetup.WidthPercentage = 100;
                tableSetup.SetWidths(new Single[] { 5, 5, 5, 5, 5, 5 });
                tableSetup.SpacingBefore = 0;

                // title pdfPage
                string sCity = row["ATIS"].ToString().Substring(0, 4);
                Phrase pSetup = new Phrase(sCity + " WEATHER CONDITIONS");
                pSetup.Font.Color = PDF.color_Black;
                pSetup.Font.SetFamily(PDF.sFont_Fixed_Width);
                pSetup.Font.SetStyle("bold");
                pSetup.Font.Size = PDF.iNormalFontSize;
                PdfPCell cSetup = new PdfPCell(pSetup);
                cSetup.BackgroundColor = PDF.background_grey;
                cSetup.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup.Border = iTextSharp.text.Rectangle.NO_BORDER;
                cSetup.Colspan = 6;
                tableSetup.AddCell(cSetup);

                // row 1
                var chuckTitle = new Chunk("WIND", PDF.font_Title_White);
                var chuckData = new Chunk(row["WIND"].ToString(), PDF.font_Title_Green);
                Phrase pSetup1 = new Phrase(chuckTitle);
                PdfPCell cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                Phrase pSetup1d = new Phrase(chuckData);
                PdfPCell cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1d.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1d);

                chuckTitle = new Chunk("CEILING", PDF.font_Title_White);
                chuckData = new Chunk(row["CEILING"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckTitle);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup1d = new Phrase(chuckData);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1d.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1d);

                chuckTitle = new Chunk("VISIBILITY", PDF.font_Title_White);
                chuckData = new Chunk(row["VISIBILITY"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckTitle);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup1d = new Phrase(chuckData);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1d.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1d);

                // row 2
                chuckTitle = new Chunk("TEMP/DP", PDF.font_Title_White);
                chuckData = new Chunk(row["TEMP"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckTitle);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup1d = new Phrase(chuckData);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1d.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1d);

                chuckTitle = new Chunk("QNH", PDF.font_Title_White);
                chuckData = new Chunk(row["QNH"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckTitle);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup1d = new Phrase(chuckData);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1d.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1d);

                chuckTitle = new Chunk("RCAM", PDF.font_Title_White);
                chuckData = new Chunk(row["RUNWAY_COND"].ToString(), PDF.font_Title_Green);
                pSetup1 = new Phrase(chuckTitle);
                cSetup1 = new PdfPCell(pSetup1);
                cSetup1.BackgroundColor = PDF.color_Black;
                cSetup1.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1.HorizontalAlignment = Element.ALIGN_RIGHT;
                cSetup1.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1);
                pSetup1d = new Phrase(chuckData);
                cSetup1d = new PdfPCell(pSetup1d);
                cSetup1d.BackgroundColor = PDF.color_Black;
                cSetup1d.VerticalAlignment = Element.ALIGN_MIDDLE;
                cSetup1d.HorizontalAlignment = Element.ALIGN_LEFT;
                cSetup1d.BorderColor = PDF.color_White;
                cSetup1d.Border = iTextSharp.text.Rectangle.NO_BORDER;
                tableSetup.AddCell(cSetup1d);

                return tableSetup;

            } catch (Exception) {
                throw;
            }
        }
    }
}
